baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'thecyber.cat - MAH CEWL BLOG'
theme = 'bilberry-hugo-theme'
[params]
  enableLightDarkTheme = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'